<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Day 3 Predict using Machine Learning</name>
   <tag></tag>
   <elementGuidId>9e34299c-1748-4f56-b669-e4dd47d9cce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.bodyTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='blockListEvent']/a/div/div[2]/div/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>d8248a70-ad10-457f-8caa-38073dc58a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bodyTitle</value>
      <webElementGuid>22750fb3-8936-4b85-bf32-5254fd87f1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Day 3: Predict using Machine Learning
                                                </value>
      <webElementGuid>4d43e7a9-b1e2-49a2-83ec-6e3147b4b344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loopevent&quot;)/li[@id=&quot;blockListEvent&quot;]/a[1]/div[@class=&quot;cardOuter&quot;]/div[@class=&quot;blockBody&quot;]/div[@class=&quot;centerBodyTitle&quot;]/h6[@class=&quot;bodyTitle&quot;]</value>
      <webElementGuid>5541bae3-d391-431f-804d-03d42682cb79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='blockListEvent']/a/div/div[2]/div/h6</value>
      <webElementGuid>b64913e3-1619-4762-a83a-ef1e970a6317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mini Class'])[1]/following::h6[1]</value>
      <webElementGuid>ee0e02dd-e5ac-4238-99a0-604248aee75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]/div/h6</value>
      <webElementGuid>8042782e-abd6-4fe9-aedf-2c63535df187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Day 3: Predict using Machine Learning
                                                ' or . = 'Day 3: Predict using Machine Learning
                                                ')]</value>
      <webElementGuid>6cf7382c-b852-4b40-bc6c-594e7e3c8bbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
