<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Event Lainnya</name>
   <tag></tag>
   <elementGuidId>9978ecdf-c9ea-4787-aeb2-5e7805b60974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eventLainnya</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='eventLainnya']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f891be50-ed48-4b1b-995a-019540450252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/event</value>
      <webElementGuid>9d0f8781-c3da-489b-ba98-47c0eea10294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventLainnya</value>
      <webElementGuid>e1614a4b-e15c-4887-87cc-774b7c10c84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lihat Event Lainnya</value>
      <webElementGuid>3b32786d-9c20-4534-9663-3fe5cb092d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventLainnya&quot;)</value>
      <webElementGuid>f1aee4ca-ab89-4076-85e6-9e88a7cabd47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='eventLainnya']</value>
      <webElementGuid>80b38465-955f-4444-ad0c-0220c7d1467c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Modal_Success']/div/div[2]/a[2]</value>
      <webElementGuid>73f0eb03-5779-40bb-b9d5-57062ccf75e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Event Lainnya')]</value>
      <webElementGuid>4dd08794-822d-4c31-9c5b-9601d6817847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day 3: Predict using Machine Learning'])[3]/following::a[2]</value>
      <webElementGuid>ba2bd0c1-f0a5-4e8a-91a3-45b1db7ed827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2010-2021 Coding.ID All rights reserved.'])[1]/preceding::a[1]</value>
      <webElementGuid>7af88479-eba3-4164-9dd2-1daf583e230e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course'])[4]/preceding::a[6]</value>
      <webElementGuid>e40037f9-cdd9-4fa1-be7a-d6684fd713aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Event Lainnya']/parent::*</value>
      <webElementGuid>a369d678-dff4-4f93-b95d-f9b78c08b0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/event')])[10]</value>
      <webElementGuid>e2b09d80-46aa-4253-8549-7317b091ff8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/a[2]</value>
      <webElementGuid>a1eca9a6-8847-4965-9bc5-25df6b485f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/event' and @id = 'eventLainnya' and (text() = ' Lihat Event Lainnya' or . = ' Lihat Event Lainnya')]</value>
      <webElementGuid>f69f3cdd-2bee-441a-b7ec-a984c895c485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
