<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Rp 170.000</name>
   <tag></tag>
   <elementGuidId>91607f1d-68aa-40c3-847e-4e6545b5ab84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='total']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1511fa1c-816f-4750-bd59-a772cedc086c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total</value>
      <webElementGuid>142421be-43a6-41ef-88d9-3b7452027213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp 170.000</value>
      <webElementGuid>bfcb6959-5b29-4638-8ed6-071ffa5f20cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total&quot;)</value>
      <webElementGuid>2c77c010-e2c7-489b-88a5-23f35de3ad2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='total']</value>
      <webElementGuid>da352877-9c8a-4cef-8e1d-d5e98d52b4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cartForm']/div[2]/h2</value>
      <webElementGuid>f0f2dc39-4f4d-46b9-9014-9ce49e377259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::h2[1]</value>
      <webElementGuid>9db4f169-665e-4211-8be1-7370e48a9c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[4]/preceding::h2[1]</value>
      <webElementGuid>82932092-315a-47db-858a-267cc6753bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::h2[1]</value>
      <webElementGuid>b9eb3915-e1c0-4490-9dc8-29a7ac533a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp 170.000']/parent::*</value>
      <webElementGuid>8f3daab9-cd3a-4b44-bad1-bf5350bd2ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/h2</value>
      <webElementGuid>4d39a795-94ba-4e12-8190-5d7aa2213bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'total' and (text() = 'Rp 170.000' or . = 'Rp 170.000')]</value>
      <webElementGuid>bed27a15-cad3-431c-9b44-5a3624e11627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
