<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Rp                                      _e82d39</name>
   <tag></tag>
   <elementGuidId>0a7456c6-7f02-48ad-abed-7bf031c7b338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='finalEventPrice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#finalEventPrice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>baa3dfcc-b440-49fa-a247-cad903142005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-5</value>
      <webElementGuid>73d5ad2f-fcf9-4341-8155-8e93297a8698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>finalEventPrice</value>
      <webElementGuid>11732ffa-db12-4c94-af8b-fd6dd50943c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp
                                                                    85.000
                                                                </value>
      <webElementGuid>03686f31-d71d-4e6b-b054-1ee606efd9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartForm&quot;)/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[1]/h3[@id=&quot;finalEventPrice&quot;]</value>
      <webElementGuid>5c7b8cf4-9802-4b78-b28a-420e123e182b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='finalEventPrice']</value>
      <webElementGuid>11d7d125-2a8c-4de0-9045-9d79c8ef23ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cartForm']/div/div/div[3]/div/h3</value>
      <webElementGuid>61b278cf-8202-425d-9fdc-a275787801a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::h3[1]</value>
      <webElementGuid>0a9a0742-97bc-45a1-be96-0172a679636a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day 4: Workshop'])[1]/following::h3[1]</value>
      <webElementGuid>26c28da3-9434-492c-8b2e-3103b53c8fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day 3: Predict using Machine Learning'])[1]/preceding::h3[1]</value>
      <webElementGuid>2c213581-6ac0-4213-a7bc-f6e073f67ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[2]/preceding::h3[2]</value>
      <webElementGuid>f888b4aa-995a-4882-8610-8366e4f22b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h3</value>
      <webElementGuid>d5c099e4-7605-43c8-875e-5ef8b6af8b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'finalEventPrice' and (text() = 'Rp
                                                                    85.000
                                                                ' or . = 'Rp
                                                                    85.000
                                                                ')]</value>
      <webElementGuid>f9d4436d-b855-4726-8b84-8e94e3c746c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
