<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ec099754-bd79-4e52-b41c-788f1f541718</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;back&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b4da620c-ca52-4ebd-9d09-91e648f447df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/arrow-left-7dc6234f1e580dcbc4523bd0ebc09deb343ef4a66f0bc9aeba22a351a37c09f0.svg</value>
      <webElementGuid>810ef6cd-70d9-43d5-9df5-0f26ba062e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>back</value>
      <webElementGuid>f245caf4-5a71-421e-a51d-5b0cbf5f63fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>456d17c8-ccd3-45a5-acd8-792e38f01290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;page-container scroll&quot;]/div[@class=&quot;page-title&quot;]/span[@class=&quot;back-icon&quot;]/img[1]</value>
      <webElementGuid>388b00b5-e75d-4dbf-9ad3-d85c0baa296a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Beli Event/Page_Coding.ID - Cart/iframe_concat(id(, , snap-midtrans, , ))_po_a43514</value>
      <webElementGuid>12a3e256-6a1c-45d1-9bd0-6466baccd79b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/span/img</value>
      <webElementGuid>e0cc6100-5713-4ec4-af30-092e56981062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='back']</value>
      <webElementGuid>f103f95e-ebb1-40b3-a2c5-ca79479bf5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>c935a6f1-f211-4c25-8662-da1ba2c69d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/arrow-left-7dc6234f1e580dcbc4523bd0ebc09deb343ef4a66f0bc9aeba22a351a37c09f0.svg' and @alt = 'back']</value>
      <webElementGuid>08464c92-3121-4c2e-8524-9e3c0e0b756e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
